version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "7860:7860"
    env_file:
      - .env
    volumes:
      - ./promots:/app/promots