version: '3'

services:
  paper-checker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paper-checker
    ports:
      - "8080:80"
    volumes:
      - ./.env:/app/.env
      - ./backend/logs:/app/backend/logs
      - ./backend/output:/app/backend/output
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai